from __future__ import annotations

CORE_RUN_COLUMNS = (
    "run_id",
    "runner_name",
    "mode",
    "timeframe",
    "status",
    "source_db",
    "input_row_count",
    "schema_version",
    "core_rule_version",
    "pivot_detection_rule_version",
    "core_event_ordering_version",
    "price_compare_policy",
    "epsilon_policy",
    "created_at",
)
SCHEMA_VERSION_COLUMNS = ("schema_version", "created_at")
PIVOT_LEDGER_COLUMNS = (
    "pivot_id",
    "symbol",
    "timeframe",
    "pivot_dt",
    "confirmed_dt",
    "pivot_type",
    "pivot_price",
    "pivot_seq_in_bar",
    "source_bar_dt",
    "run_id",
    "schema_version",
    "core_rule_version",
    "pivot_detection_rule_version",
    "created_at",
)
STRUCTURE_LEDGER_COLUMNS = (
    "primitive_id",
    "pivot_id",
    "structure_context",
    "reference_pivot_id",
    "reference_price",
    "primitive",
    "direction_context",
    "symbol",
    "timeframe",
    "pivot_dt",
    "run_id",
    "schema_version",
    "core_rule_version",
    "created_at",
)
WAVE_LEDGER_COLUMNS = (
    "wave_id",
    "symbol",
    "timeframe",
    "wave_seq",
    "direction",
    "birth_type",
    "start_pivot_id",
    "candidate_guard_pivot_id",
    "confirm_pivot_id",
    "confirm_dt",
    "wave_core_state",
    "terminated_dt",
    "terminated_by_break_id",
    "final_progress_extreme_pivot_id",
    "final_progress_extreme_price",
    "final_guard_pivot_id",
    "final_guard_price",
    "run_id",
    "schema_version",
    "core_rule_version",
    "created_at",
    "current_effective_guard_pivot_id",
    "current_effective_guard_price",
)
BREAK_LEDGER_COLUMNS = (
    "break_id",
    "wave_id",
    "direction",
    "guard_pivot_id",
    "break_dt",
    "break_price",
    "system_state_after",
    "run_id",
    "schema_version",
    "core_rule_version",
    "created_at",
    "broken_guard_pivot_id",
)
TRANSITION_LEDGER_COLUMNS = (
    "transition_id",
    "old_wave_id",
    "break_id",
    "old_direction",
    "old_progress_extreme_pivot_id",
    "old_progress_extreme_price",
    "break_dt",
    "state",
    "confirmed_dt",
    "new_wave_id",
    "run_id",
    "schema_version",
    "core_rule_version",
    "created_at",
    "broken_guard_pivot_id",
    "transition_boundary_high",
    "transition_boundary_low",
)
CANDIDATE_LEDGER_COLUMNS = (
    "candidate_id",
    "transition_id",
    "candidate_guard_pivot_id",
    "candidate_direction",
    "candidate_dt",
    "is_active_at_close",
    "invalidated_by_candidate_id",
    "reference_progress_extreme_price",
    "confirmed_by_pivot_id",
    "confirmed_wave_id",
    "run_id",
    "schema_version",
    "core_rule_version",
    "created_at",
    "candidate_status",
    "confirmation_pivot_id",
    "new_wave_id",
    "candidate_event_type",
)
CORE_STATE_SNAPSHOT_COLUMNS = (
    "snapshot_id",
    "symbol",
    "timeframe",
    "bar_dt",
    "system_state",
    "wave_id",
    "old_wave_id",
    "wave_core_state",
    "direction",
    "progress_updated",
    "transition_span",
    "guard_boundary_price",
    "current_effective_guard_pivot_id",
    "current_effective_guard_price",
    "transition_id",
    "break_id",
    "transition_boundary_high",
    "transition_boundary_low",
    "active_candidate_id",
    "active_candidate_guard_pivot_id",
    "confirmation_pivot_id",
    "new_wave_id",
    "run_id",
    "schema_version",
    "core_rule_version",
    "pivot_detection_rule_version",
    "core_event_ordering_version",
    "price_compare_policy",
    "epsilon_policy",
    "created_at",
)
LIFESPAN_RUN_COLUMNS = (
    "run_id",
    "runner_name",
    "mode",
    "timeframe",
    "status",
    "source_core_run_id",
    "input_wave_count",
    "schema_version",
    "lifespan_rule_version",
    "sample_version",
    "pivot_detection_rule_version",
    "core_event_ordering_version",
    "price_compare_policy",
    "epsilon_policy",
    "created_at",
)
LIFESPAN_SNAPSHOT_COLUMNS = (
    "snapshot_id",
    "wave_id",
    "old_wave_id",
    "symbol",
    "timeframe",
    "bar_dt",
    "wave_core_state",
    "system_state",
    "direction",
    "progress_updated",
    "new_count",
    "no_new_span",
    "transition_span",
    "life_state",
    "position_quadrant",
    "update_rank",
    "stagnation_rank",
    "guard_boundary_price",
    "run_id",
    "schema_version",
    "lifespan_rule_version",
    "sample_version",
    "created_at",
    "transition_boundary_high",
    "transition_boundary_low",
    "active_candidate_guard_pivot_id",
    "confirmation_pivot_id",
    "new_wave_id",
    "birth_type",
    "candidate_wait_span",
    "candidate_replacement_count",
    "confirmation_distance_abs",
    "confirmation_distance_pct",
)
LIFESPAN_PROFILE_COLUMNS = (
    "profile_id",
    "timeframe",
    "direction",
    "sample_version",
    "metric_name",
    "sample_cutoff",
    "sample_size",
    "p25",
    "p50",
    "p75",
    "p90",
    "run_id",
    "schema_version",
    "lifespan_rule_version",
    "created_at",
)
SAMPLE_VERSION_COLUMNS = (
    "sample_version",
    "universe",
    "timeframe",
    "direction",
    "birth_type",
    "sample_cutoff_rule",
    "created_at",
)
RULE_VERSION_COLUMNS = (
    "lifespan_rule_version",
    "low_update_threshold",
    "high_update_threshold",
    "high_stagnation_threshold",
    "created_at",
)
SERVICE_RUN_COLUMNS = (
    "run_id",
    "runner_name",
    "mode",
    "timeframe",
    "status",
    "source_core_run_id",
    "source_lifespan_run_id",
    "published_row_count",
    "schema_version",
    "service_version",
    "pivot_detection_rule_version",
    "core_event_ordering_version",
    "price_compare_policy",
    "epsilon_policy",
    "created_at",
)
WAVE_POSITION_COLUMNS = (
    "symbol",
    "timeframe",
    "bar_dt",
    "system_state",
    "wave_id",
    "old_wave_id",
    "wave_core_state",
    "direction",
    "new_count",
    "no_new_span",
    "transition_span",
    "update_rank",
    "stagnation_rank",
    "life_state",
    "position_quadrant",
    "guard_boundary_price",
    "sample_scope",
    "sample_version",
    "lifespan_rule_version",
    "service_version",
    "run_id",
    "schema_version",
    "source_core_run_id",
    "source_lifespan_run_id",
    "created_at",
    "transition_boundary_high",
    "transition_boundary_low",
    "active_candidate_guard_pivot_id",
    "confirmation_pivot_id",
    "new_wave_id",
    "birth_type",
    "candidate_wait_span",
    "candidate_replacement_count",
    "confirmation_distance_abs",
    "confirmation_distance_pct",
)
INTERFACE_AUDIT_COLUMNS = (
    "audit_id",
    "run_id",
    "check_name",
    "severity",
    "status",
    "failed_count",
    "sample_payload",
    "created_at",
)
V13_TRACE_COLUMNS = [
    ("transition_boundary_high", "double"),
    ("transition_boundary_low", "double"),
    ("active_candidate_guard_pivot_id", "varchar"),
    ("confirmation_pivot_id", "varchar"),
    ("new_wave_id", "varchar"),
    ("birth_type", "varchar"),
    ("candidate_wait_span", "bigint"),
    ("candidate_replacement_count", "bigint"),
    ("confirmation_distance_abs", "double"),
    ("confirmation_distance_pct", "double"),
]
CORE_STATE_SNAPSHOT_COMPAT_COLUMNS = [
    ("current_effective_guard_pivot_id", "varchar"),
    ("current_effective_guard_price", "double"),
    ("transition_id", "varchar"),
    ("break_id", "varchar"),
    ("transition_boundary_high", "double"),
    ("transition_boundary_low", "double"),
    ("active_candidate_id", "varchar"),
    ("active_candidate_guard_pivot_id", "varchar"),
    ("confirmation_pivot_id", "varchar"),
    ("new_wave_id", "varchar"),
    ("pivot_detection_rule_version", "varchar"),
    ("core_event_ordering_version", "varchar"),
    ("price_compare_policy", "varchar"),
    ("epsilon_policy", "varchar"),
]


def insert_columns_sql(table_name: str, columns: tuple[str, ...]) -> str:
    column_sql = ", ".join(columns)
    value_sql = ", ".join(["?"] * len(columns))
    return f"insert into {table_name} ({column_sql}) values ({value_sql})"
